[archive]
build_output_dir = 'Built'
archive_location = '\\nirvana\Measurements\VeriStandAddons\download_item_package'

[package]
type = 'nipkg'
payload_dir = 'Built'
install_destination = '' # Create virtual package with no payload

[notification]
type = 'teams'
